process.env.TZ = 'America/Bogota';
process.on('uncaughtExceptionMonitor', error => console.error('::error::' + String(error.stack || error).slice(0, 10000).replaceAll('%', '%25').replaceAll('\n', '%0A').replaceAll('\r', '%0D')));
import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const browser = await chromium.launch();
try {
  const page = await browser.newPage({ timezoneId: 'America/Bogota', viewport: { width: 1440, height: 1050 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(process.env.APP_URL || 'http://localhost:5173');
  await page.getByLabel('Clave de acceso').fill('0000000');
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await page.getByText('Esa clave no es correcta. Inténtalo de nuevo.').waitFor();
  await page.getByLabel('Clave de acceso').fill('1357955');
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await page.getByRole('heading', { name: '¿Cómo va el consultorio?' }).waitFor();
  const nataliaChart = page.getByRole('region', { name: 'Gastos por categoría', exact: true });
  const nataliaScope = nataliaChart.getByRole('group', { name: 'Espacio de los gastos', exact: true });
  assert.equal(await nataliaScope.getByRole('button', { name: 'Ver gastos personales', exact: true }).getAttribute('aria-pressed'), 'true');
  assert.doesNotMatch(await nataliaChart.getByRole('img').getAttribute('aria-label'), /Laboratorio/);
  const nataliaCash = await page.locator('.daily-balance h1').textContent();
  await nataliaScope.getByRole('button', { name: 'Ver gastos del consultorio', exact: true }).click();
  assert.match(await nataliaChart.getByRole('img').getAttribute('aria-label'), /Laboratorio/);
  await nataliaChart.getByRole('button', { name: 'Ver gastos de Laboratorio', exact: true }).click();
  await nataliaChart.locator('.category-detail').getByText('Trabajo de laboratorio', { exact: true }).waitFor();
  assert.equal(await page.locator('.daily-balance h1').textContent(), nataliaCash);
  await nataliaScope.getByRole('button', { name: 'Ver gastos personales', exact: true }).click();
  assert.equal(await nataliaChart.locator('.category-detail').count(), 0);

  await page.getByRole('button', { name: 'Recibí dinero', exact: true }).click();
  await page.getByRole('button', { name: 'Aleja', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Cerrar', exact: true }).click();
  assert.equal(await page.getByRole('navigation').count(), 0, 'Una sola pantalla sin navegación de dashboard');
  await page.screenshot({ path: 'artifacts/desktop.png', fullPage: true });
  for (const width of [375, 320]) {
    await page.setViewportSize({ width, height: 812 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `Sin desbordamiento a ${width}px`);
    if (width === 375) await page.screenshot({ path: 'artifacts/mobile.png', fullPage: true });
  }
  await page.setViewportSize({ width: 375, height: 812 });
  await page.getByLabel('Opciones').click();
  await page.getByRole('button', { name: 'Empezar desde cero' }).click();
  await page.getByRole('button', { name: 'Borrar y empezar' }).click();
  assert.match(await page.locator('.daily-balance h1').textContent(), /\$\s*0/);
  await page.getByLabel('Opciones').click();
  await page.getByRole('button', { name: 'Recibí dinero', exact: true }).click();
  await page.getByLabel('Monto en pesos', { exact: true }).fill('500000');
  await page.getByRole('button', { name: 'Déntica', exact: true }).click();
  await page.getByText('Cambiar fecha o agregar detalles').click();
  const earlier = new Date(); earlier.setMonth(earlier.getMonth() - 1); earlier.setDate(15);
  const previousDate = `${earlier.getFullYear()}-${String(earlier.getMonth() + 1).padStart(2, '0')}-15`;
  await page.locator('input[name=date]').fill(previousDate);
  await page.getByRole('button', { name: 'Guardar ingreso', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.match(await page.locator('.daily-balance h1').textContent(), /500\.000/);
  await page.getByRole('button', { name: 'Recibí dinero', exact: true }).click();
  await page.getByLabel('Monto en pesos', { exact: true }).fill('200000');
  await page.getByRole('button', { name: 'Sedato', exact: true }).click();
  await page.getByRole('button', { name: 'Guardar ingreso', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.match(await page.locator('.daily-balance h1').textContent(), /700\.000/);
  // El gasto se guarda sin abrir detalles ni escribir nota, categoría o fecha.
  await page.getByRole('button', { name: 'Pagué algo', exact: true }).click();
  await page.getByLabel('Monto en pesos', { exact: true }).fill('20000');
  assert.equal(await page.locator('.optional-details').getAttribute('open'), null);
  await page.getByRole('button', { name: 'Guardar gasto', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.match(await page.locator('.daily-balance h1').textContent(), /680\.000/);
  await page.getByRole('button', { name: 'Pagué algo', exact: true }).click();
  await page.getByLabel('Monto en pesos', { exact: true }).fill('100000');
  await page.getByRole('button', { name: 'Consultorio', exact: true }).click();
  await page.getByRole('button', { name: 'Guardar gasto', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.match(await page.locator('.daily-balance h1').textContent(), /580\.000/);
  assert.match(await page.locator('.office-totals').textContent(), /100\.000/);
  await page.reload();
  await page.getByRole('heading', { name: '¿Cómo va el consultorio?' }).waitFor();
  assert.match(await page.locator('.daily-balance h1').textContent(), /580\.000/);
  await page.getByRole('button', { name: 'Editar Gasto personal', exact: true }).click();
  await page.getByLabel('Monto en pesos', { exact: true }).fill('30000');
  await page.getByRole('button', { name: 'Guardar gasto', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.match(await page.locator('.daily-balance h1').textContent(), /570\.000/);
  await page.getByRole('button', { name: 'Recibí dinero', exact: true }).click();
  await page.getByLabel('Monto en pesos', { exact: true }).fill('200000');
  await page.getByText('Cambiar fecha o agregar detalles').click();
  await page.getByRole('button', { name: 'Ya entregados', exact: true }).click();
  await page.locator('input[name=reserved]').fill('50000');
  await page.getByRole('button', { name: 'Guardar ingreso', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.match(await page.locator('.daily-balance h1').textContent(), /720\.000/);
  assert.match(await page.locator('.office-totals').textContent(), /200\.000/);
  await page.getByRole('button', { name: 'Pagué algo', exact: true }).click();
  await page.getByLabel('Monto en pesos', { exact: true }).fill('30000');
  await page.getByRole('button', { name: 'Consultorio', exact: true }).click();
  await page.getByText('Cambiar fecha o agregar detalles').click();
  await page.getByRole('textbox', { name: 'Concepto', exact: true }).fill('Laboratorio');
  await page.getByLabel('Lo pagué con dinero apartado para tratamientos').check();
  await page.getByRole('button', { name: 'Guardar gasto', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.match(await page.locator('.daily-balance h1').textContent(), /720\.000/);
  await page.getByRole('button', { name: 'Ver anteriores', exact: true }).click();
  assert.equal(await page.locator('.recent-list li').count(), 6);
  await page.getByRole('button', { name: 'Editar Laboratorio', exact: true }).click();
  await page.getByRole('button', { name: 'Eliminar este movimiento', exact: true }).click();
  await page.getByRole('button', { name: 'Eliminar movimiento', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.equal(await page.locator('.recent-list li').count(), 5);
  assert.match(await page.locator('.daily-balance h1').textContent(), /720\.000/);
  await page.getByLabel('Opciones').click();
  const download = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Descargar movimientos' }).click();
  assert.equal((await download).suggestedFilename(), 'natalia-movimientos.csv');
  await page.getByRole('button', { name: 'Cómo funciona' }).click();
  await page.keyboard.press('Escape');
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  // Nombres de fuentes, clasificación de gasto y periodo se conservan en el CSV.
  await page.getByRole('button', { name: 'Fuentes de ingreso', exact: true }).click();
  await page.getByRole('button', { name: 'Cambiar nombre de Déntica' }).click();
  await page.locator('input[name=source_name]').fill('Clínica Sonrisa');
  await page.getByRole('button', { name: 'Guardar nombre' }).click();
  await page.getByRole('button', { name: 'Cambiar nombre de Clínica Sonrisa' }).waitFor();
  await page.locator('input[name=source_name]').fill('Clínica Nueva');
  await page.locator('select[name=source_context]').selectOption('Clínica 2');
  await page.getByRole('button', { name: 'Agregar fuente' }).click();
  await page.getByRole('button', { name: 'Cambiar nombre de Clínica Nueva' }).waitFor();
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: 'Editar Pago de Déntica', exact: true }).click();
  await page.locator('input[name=competence_date]').fill('2026-08-15');
  await page.getByRole('button', { name: 'Guardar ingreso', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await page.getByRole('button', { name: 'Editar Gasto personal', exact: true }).click();
  await page.locator('select[name=category]').selectOption('Alimentación');
  await page.getByRole('button', { name: 'Guardar gasto', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await nataliaScope.getByRole('button', { name: 'Ver gastos personales', exact: true }).click();
  assert.match(await nataliaChart.getByRole('button', { name: 'Ver gastos de Alimentación', exact: true }).textContent(), /Alimentación.*30\.000/);
  await page.reload();
  await page.getByRole('heading', { name: '¿Cómo va el consultorio?' }).waitFor();
  const stored = await page.evaluate(() => JSON.parse(localStorage.getItem('natalia-finances-v1')));
  assert(stored.sources.some(s => s.name === 'Clínica Sonrisa'));
  assert(stored.sources.some(s => s.name === 'Clínica Nueva'));
  assert(stored.items.some(t => t.competence_date === '2026-08-15'));
  await page.getByLabel('Opciones').click();
  const enrichedDownload = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Descargar movimientos' }).click();
  const csvPath = await (await enrichedDownload).path();
  const { readFile } = await import('node:fs/promises');
  const csv = await readFile(csvPath, 'utf8');
  assert(csv.includes('ID persona'));
  assert(csv.includes('Fecha periodo'));
  assert(csv.includes('Clínica Sonrisa'));
  assert(csv.includes('2026-08-15'));
  assert(csv.includes('Alimentación'));
  assert(!csv.includes('"\'-30000"'), 'Flujo negativo debe exportarse como número');
  assert.equal(await page.getByRole('heading', { name: 'Notas, tal como pasó' }).count(), 0);
  await page.getByRole('button', { name: 'Tabla', exact: true }).click();
  await page.getByRole('columnheader', { name: 'Fecha', exact: true }).waitFor();
  assert.equal(await page.getByRole('columnheader', { name: 'Concepto' }).count(), 1);
  assert.equal(await page.getByRole('columnheader', { name: 'Moneda' }).count(), 1);
  for (const width of [320, 375]) {
    await page.setViewportSize({ width, height: 812 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'Tabla dentro de pantalla');
  }
  if (await page.locator('.options-menu').getAttribute('open') === null) await page.getByLabel('Opciones').click();
  await page.getByRole('button', { name: 'Salir', exact: true }).click();
  await page.getByLabel('Clave de acceso').fill('123456');
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await page.getByRole('button', { name: 'Entrada', exact: true }).waitFor();
  assert.match(await page.locator('.daily-brand').textContent(), /Diego/);
  assert.equal(await page.getByRole('heading', { name: '¿Cómo va el consultorio?' }).count(), 0);
  await page.getByRole('button', { name: 'Entrada', exact: true }).click();
  assert.equal(await page.getByRole('button', { name: 'Consultorio', exact: true }).count(), 0);
  assert.equal(await page.getByRole('button', { name: 'Déntica', exact: true }).count(), 0);
  await page.getByLabel('Moneda del movimiento').selectOption('USD');
  await page.getByLabel('Monto en dólares', { exact: true }).fill('150.25');
  await page.getByLabel('Concepto', { exact: true }).fill('Pago de Diego a Bancolombia');
  await page.getByRole('button', { name: 'Guardar ingreso', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await page.getByRole('group', { name: 'Moneda del saldo' }).getByRole('button', { name: 'USD', exact: true }).click();
  assert.match(await page.locator('.daily-balance h1').textContent(), /150,25.*USD/);
  await page.getByRole('button', { name: 'Salida', exact: true }).click();
  await page.getByLabel('Monto en dólares', { exact: true }).fill('20.10');
  assert.equal(await page.getByRole('button', { name: 'Consultorio', exact: true }).count(), 0);
  await page.getByRole('button', { name: 'Guardar gasto', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.match(await page.locator('.daily-balance h1').textContent(), /130,15.*USD/);
  const chart = page.getByRole('region', { name: 'Gastos por categoría', exact: true });
  assert.match(await chart.getByRole('img').getAttribute('aria-label'), /20,10.*USD.*100\.0%/);
  const beforeCategory = await page.evaluate(() => localStorage.getItem('diego-finances-v1'));
  await chart.getByRole('button', { name: 'Ver gastos de Otros / sin clasificar', exact: true }).click();
  await chart.locator('.category-detail').getByText('Gasto personal', { exact: true }).waitFor();
  assert.match(await chart.locator('.category-donut').textContent(), /20,10.*USD/);
  assert.equal(await page.evaluate(() => localStorage.getItem('diego-finances-v1')), beforeCategory, 'Explorar categorías no modifica el registro');
  for (const width of [375,320]) {
    await page.setViewportSize({ width, height: 812 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `Dona sin desbordamiento a ${width}px`);
  }
  await chart.getByRole('button', { name: 'Ver total', exact: true }).click();
  await chart.getByRole('button', { name: 'Ver gastos de Otros / sin clasificar', exact: true }).click();
  await chart.getByRole('button', { name: 'Categorizar Gasto personal', exact: true }).click();
  await page.getByLabel('Categoría', { exact: true }).selectOption('Deudas');
  await page.getByRole('button', { name: 'Guardar respuesta', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await chart.getByRole('button', { name: 'Ver gastos de Deudas', exact: true }).click();
  await chart.locator('.category-detail').getByText('Gasto personal', { exact: true }).waitFor();
  assert.match(await page.locator('.daily-balance h1').textContent(), /130,15.*USD/);
  await chart.getByRole('button', { name: 'Categorizar Gasto personal', exact: true }).click();
  await page.getByLabel('Categoría', { exact: true }).selectOption('Servicios');
  await page.getByRole('button', { name: 'Guardar respuesta', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });


  await page.getByRole('group', { name: 'Moneda del saldo' }).getByRole('button', { name: 'COP', exact: true }).click();
  assert.match(await page.locator('.daily-balance h1').textContent(), /\$\s*0.*COP/);
  await chart.getByText('Sin gastos registrados este mes en COP.', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Entrada', exact: true }).click();
  await page.getByLabel('Monto en pesos', { exact: true }).fill('200000');
  await page.getByRole('button', { name: 'Guardar ingreso', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.match(await page.locator('.daily-balance h1').textContent(), /200\.000.*COP/);

  await page.getByRole('button', { name: 'Tabla', exact: true }).click();
  await page.getByRole('cell', { name: 'Pago de Diego a Bancolombia' }).waitFor();
  assert.match(await page.locator('.income-total').textContent(), /200\.000.*COP/);
  await page.getByRole('group', { name: 'Moneda del saldo' }).getByRole('button', { name: 'USD', exact: true }).click();
  assert.match(await page.locator('.income-total').textContent(), /150,25.*USD/);
  assert.match(await page.locator('.expense-total').textContent(), /20,10.*USD/);
  assert.equal(await page.locator('.expense-total').evaluate(e => getComputedStyle(e).color), 'rgb(192, 71, 71)');
  await page.reload();
  await page.getByRole('button', { name: 'Tabla', exact: true }).click();
  await page.getByRole('cell', { name: 'Pago de Diego a Bancolombia' }).waitFor();
  assert.match(await page.locator('.daily-brand').textContent(), /Diego/);
  if (await page.locator('.options-menu').getAttribute('open') === null) await page.getByLabel('Opciones').click();
  await page.getByRole('button', { name: 'Salir', exact: true }).click();
  await page.getByLabel('Clave de acceso').fill('1357955');
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await page.getByRole('heading', { name: '¿Cómo va el consultorio?' }).waitFor();
  assert.equal(await page.getByText('Pago de Diego a Bancolombia', { exact: true }).count(), 0);
  const balanceBefore = await page.locator('.daily-balance h1').textContent();
  await page.getByRole('button', { name: 'Recibí dinero', exact: true }).click();
  await page.getByLabel('Monto en pesos', { exact: true }).fill('1650000');
  await page.getByRole('button', { name: 'Consultorio', exact: true }).click();
  await page.getByLabel('Concepto', { exact: true }).fill('Abono pendiente caso de prueba');
  await page.getByRole('button', { name: 'Aún pendientes', exact: true }).click();
  await page.getByRole('button', { name: 'Guardar ingreso', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.equal(await page.locator('.daily-balance h1').textContent(), balanceBefore);
  const recordsBeforeTable = await page.evaluate(() => localStorage.getItem('natalia-finances-v1'));
  await page.getByText('Ver cobros y abonos', { exact: true }).click();
  const receiptTable = page.getByRole('region', { name: 'Cobros del consultorio', exact: true });
  const pendingReceipt = receiptTable.getByRole('row').filter({ hasText: 'Abono pendiente caso de prueba' });
  assert.match(await pendingReceipt.textContent(), /1\.650\.000.*Pendiente/);
  assert.equal(await page.evaluate(() => localStorage.getItem('natalia-finances-v1')), recordsBeforeTable, 'Leer cobros no modifica movimientos ni saldos');
  assert.equal(await page.locator('.daily-balance h1').textContent(), balanceBefore);
  await page.setViewportSize({ width: 320, height: 812 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'Tabla de cobros sin desbordar celular');
  await page.setViewportSize({ width: 375, height: 812 });
  const incomeBeforeRelease = await page.locator('.income-total').textContent();
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: 'Entregado', exact: true }).click();
  await page.getByRole('button', { name: 'Entregado', exact: true }).waitFor({ state: 'hidden' });
  assert.equal(await page.locator('.income-total').textContent(), incomeBeforeRelease);
  assert.notEqual(await page.locator('.daily-balance h1').textContent(), balanceBefore);
  await page.getByRole('button', { name: 'Pagué algo', exact: true }).click();
  await page.getByLabel('Monto en pesos', { exact: true }).fill('10000');
  await page.getByLabel('Concepto', { exact: true }).fill('Didi regreso a casa');
  await page.getByText('Se guardará como Personal · Transporte. Puedes cambiar la categoría.').waitFor();
  await page.getByRole('button', { name: 'Guardar gasto', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  const earlierButton = page.getByRole('button', { name: 'Ver anteriores', exact: true });
  if (await earlierButton.count()) await earlierButton.click();
  await page.getByRole('button', { name: 'Editar Didi regreso a casa' }).click();
  assert.equal(await page.locator('select[name=category]').inputValue(), 'Transporte');
  await page.getByRole('button', { name: 'Cerrar', exact: true }).click();
  // A clarification updates one existing row and never registers the money twice.
  await page.getByRole('button', { name: 'Pagué algo', exact: true }).click();
  await page.getByLabel('Monto en pesos', { exact: true }).fill('290000');
  await page.getByLabel('Concepto', { exact: true }).fill('Compra lunia');
  await page.getByRole('button', { name: 'Guardar gasto', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  const expenseBalance = await page.locator('.daily-balance h1').textContent();
  const countBeforeAnswer = await page.evaluate(() => JSON.parse(localStorage.getItem('natalia-finances-v1')).items.length);
  const pencil = page.getByRole('button', { name: 'Aclarar Compra lunia', exact: true });
  assert.equal(await pencil.isVisible(), true);
  assert.ok((await pencil.boundingBox()).width >= 44);
  await pencil.click();
  await page.getByText('¿Qué compraste y para qué fue?', { exact: true }).waitFor();
  await page.getByLabel('Concepto', { exact: true }).fill('Compra ropa en Lunia');
  await page.getByLabel('Categoría', { exact: true }).selectOption('Compras');
  await page.getByRole('button', { name: 'Guardar respuesta', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.equal(await page.locator('.daily-balance h1').textContent(), expenseBalance);
  assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('natalia-finances-v1')).items.length), countBeforeAnswer);
  assert.equal(await page.getByRole('button', { name: 'Aclarar Compra ropa en Lunia', exact: true }).count(), 0);
  await page.getByRole('button', { name: 'Recibí dinero', exact: true }).click();
  await page.getByLabel('Monto en pesos', { exact: true }).fill('1520876');
  await page.getByRole('button', { name: 'Consultorio', exact: true }).click();
  await page.getByLabel('Concepto', { exact: true }).fill('Pacientes por aclarar');
  await page.getByRole('button', { name: 'Guardar ingreso', exact: true }).click();
  await page.getByText('Indica si los tratamientos están entregados o pendientes.', { exact: true }).waitFor();
  assert.equal(await page.getByRole('dialog').count(), 1, 'No guarda un cobro del consultorio sin responder');
  await page.getByRole('button', { name: 'Ya entregados', exact: true }).click();
  await page.getByRole('button', { name: 'Guardar ingreso', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  const incomesBeforeAnswer = await page.locator('.income-total').textContent();
  // Simulate a legacy payment, as Natalia already has in Supabase.
  await page.evaluate(() => {
    const key = 'natalia-finances-v1', data = JSON.parse(localStorage.getItem(key));
    data.items.find(t => t.description === 'Pacientes por aclarar').category = 'Otros';
    localStorage.setItem(key, JSON.stringify(data));
  });
  await page.reload();
  const reminder = page.getByRole('region', { name: 'Movimiento por aclarar', exact: true });
  await reminder.getByText('¿Ya entregaste los tratamientos o hay pagos anticipados?', { exact: true }).waitFor();
  assert.match(await reminder.textContent(), /Pacientes por aclarar/);
  await reminder.getByRole('button', { name: 'Después', exact: true }).click();
  await reminder.waitFor({ state: 'hidden' });
  await page.reload();
  await reminder.getByRole('button', { name: 'Responder', exact: true }).click();
  await page.getByRole('button', { name: 'Aún pendientes', exact: true }).click();
  await page.getByRole('button', { name: 'Guardar respuesta', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.equal(await page.locator('.income-total').textContent(), incomesBeforeAnswer);
  assert.equal(await page.locator('.daily-balance h1').textContent(), expenseBalance);
  await page.reload();
  const clarified = await page.evaluate(() => JSON.parse(localStorage.getItem('natalia-finances-v1')).items.find(t => t.description === 'Pacientes por aclarar'));
  assert.equal(clarified.amount, 1520876); assert.equal(clarified.reserved, 1520876); assert.equal(clarified.patient_advance, true);
  assert.doesNotMatch((await page.getByRole('region', { name: 'Movimiento por aclarar', exact: true }).allTextContents()).join(''), /Pacientes por aclarar/);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  // New office questions appear on entry and save context independently of the ledger.
  await page.evaluate(() => {
    const data=JSON.parse(localStorage.getItem('natalia-finances-v1'));
    const date=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Bogota',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
    data.items.push({id:crypto.randomUUID(),date,kind:'income',amount:1511547,currency:'COP',context:'Consultorio',category:'Tratamiento',description:'Consultorio · Incluye tratamientos entregados y pendientes; cobro apartado hasta aclarar cada caso.',reserved:1511547,patient_advance:true,from_reserve:false,person_tag:'natalia'});
    data.items.push({id:crypto.randomUUID(),date,kind:'expense',amount:180000,currency:'COP',context:'Consultorio',category:'Servicios',description:'Pago Dianita auxiliar',reserved:0,from_reserve:false,person_tag:'natalia'});
    localStorage.setItem('natalia-finances-v1',JSON.stringify(data));localStorage.removeItem('natalia-office-answers-v1');
  });
  await page.reload();
  const officeQuestions=page.getByRole('region',{name:'Preguntas del consultorio',exact:true});
  await officeQuestions.getByText('De este cobro, ¿cuánto corresponde a tratamientos ya terminados?',{exact:true}).waitFor();
  await officeQuestions.getByRole('button',{name:'Responder después sobre el consultorio',exact:true}).click();
  await officeQuestions.waitFor({state:'hidden'});
  await page.reload();
  await officeQuestions.getByLabel('Monto de tratamientos terminados',{exact:true}).waitFor();
  const beforeOfficeAnswers=await page.evaluate(()=>localStorage.getItem('natalia-finances-v1'));
  await officeQuestions.getByLabel('Monto de tratamientos terminados',{exact:true}).fill('500000');
  await officeQuestions.getByRole('button',{name:'Guardar respuesta del consultorio',exact:true}).click();
  await officeQuestions.getByLabel('Tratamientos y pagos pendientes',{exact:true}).fill('Falta entregar dos casos; laboratorio de varios casos, costo aún pendiente.');
  await officeQuestions.getByRole('button',{name:'Guardar respuesta del consultorio',exact:true}).click();
  await officeQuestions.getByLabel('Periodo del pago a la auxiliar',{exact:true}).selectOption('week');
  await officeQuestions.getByRole('button',{name:'Guardar respuesta del consultorio',exact:true}).click();
  await officeQuestions.waitFor({state:'hidden'});
  assert.equal(await page.evaluate(()=>localStorage.getItem('natalia-finances-v1')),beforeOfficeAnswers,'Responder no modifica movimientos ni reservas');
  await page.reload();await page.getByRole('heading',{name:'¿Cómo va el consultorio?',exact:true}).waitFor();
  assert.equal(await officeQuestions.count(),0,'Las preguntas respondidas no se repiten');
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('natalia-office-answers-v1')).length),3);
  assert.deepEqual(errors, []);
  console.log('OK: pantalla única, gasto sin nota/fecha/categoría, pagos en distintas fechas, saldo entre meses, consultorio, reservas existentes, edición/eliminación, persistencia, CSV y celular 320/375 px.');
} finally { await browser.close(); }
