process.env.TZ = 'America/Bogota';
process.on('uncaughtExceptionMonitor', error => console.error('::error::' + String(error.stack || error).slice(0, 10000).replaceAll('%', '%25').replaceAll('\n', '%0A').replaceAll('\r', '%0D')));
import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const browser = await chromium.launch();
try {
  const page = await browser.newPage({ timezoneId: 'America/Bogota', viewport: { width: 1440, height: 1050 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(process.env.APP_URL || 'http://localhost:5173');
  await page.getByLabel('Clave de acceso').fill('0000000');
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await page.getByText('Esa clave no es correcta. Inténtalo de nuevo.').waitFor();
  await page.getByLabel('Clave de acceso').fill('1357955');
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await page.getByRole('heading', { name: '¿Cómo va el consultorio?' }).waitFor();
  assert.equal(await page.getByRole('navigation').count(), 0, 'Una sola pantalla sin navegación de dashboard');
  await page.screenshot({ path: 'artifacts/desktop.png', fullPage: true });
  for (const width of [375, 320]) {
    await page.setViewportSize({ width, height: 812 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `Sin desbordamiento a ${width}px`);
    if (width === 375) await page.screenshot({ path: 'artifacts/mobile.png', fullPage: true });
  }
  await page.setViewportSize({ width: 375, height: 812 });
  await page.getByLabel('Opciones').click();
  await page.getByRole('button', { name: 'Empezar desde cero' }).click();
  await page.getByRole('button', { name: 'Borrar y empezar' }).click();
  assert.match(await page.locator('.daily-balance h1').textContent(), /\$\s*0/);
  await page.getByLabel('Opciones').click();
  await page.getByRole('button', { name: 'Recibí dinero', exact: true }).click();
  await page.getByLabel('Monto en pesos', { exact: true }).fill('500000');
  await page.getByRole('button', { name: 'Clínica 1', exact: true }).click();
  await page.getByText('Cambiar fecha o agregar detalles').click();
  const earlier = new Date(); earlier.setMonth(earlier.getMonth() - 1); earlier.setDate(15);
  const previousDate = `${earlier.getFullYear()}-${String(earlier.getMonth() + 1).padStart(2, '0')}-15`;
  await page.locator('input[name=date]').fill(previousDate);
  await page.getByRole('button', { name: 'Guardar ingreso', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.match(await page.locator('.daily-balance h1').textContent(), /500\.000/);
  await page.getByRole('button', { name: 'Recibí dinero', exact: true }).click();
  await page.getByLabel('Monto en pesos', { exact: true }).fill('200000');
  await page.getByRole('button', { name: 'Clínica 2', exact: true }).click();
  await page.getByRole('button', { name: 'Guardar ingreso', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.match(await page.locator('.daily-balance h1').textContent(), /700\.000/);
  // El gasto se guarda sin abrir detalles ni escribir nota, categoría o fecha.
  await page.getByRole('button', { name: 'Pagué algo', exact: true }).click();
  await page.getByLabel('Monto en pesos', { exact: true }).fill('20000');
  assert.equal(await page.locator('.optional-details').getAttribute('open'), null);
  await page.getByRole('button', { name: 'Guardar gasto', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.match(await page.locator('.daily-balance h1').textContent(), /680\.000/);
  await page.getByRole('button', { name: 'Pagué algo', exact: true }).click();
  await page.getByLabel('Monto en pesos', { exact: true }).fill('100000');
  await page.getByRole('button', { name: 'Consultorio', exact: true }).click();
  await page.getByRole('button', { name: 'Guardar gasto', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.match(await page.locator('.daily-balance h1').textContent(), /580\.000/);
  assert.match(await page.locator('.office-note > p').textContent(), /Le faltan.*100\.000/);
  await page.reload();
  await page.getByRole('heading', { name: '¿Cómo va el consultorio?' }).waitFor();
  assert.match(await page.locator('.daily-balance h1').textContent(), /580\.000/);
  await page.getByRole('button', { name: 'Editar Gasto personal', exact: true }).click();
  await page.getByLabel('Monto en pesos', { exact: true }).fill('30000');
  await page.getByRole('button', { name: 'Guardar gasto', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.match(await page.locator('.daily-balance h1').textContent(), /570\.000/);
  await page.getByRole('button', { name: 'Recibí dinero', exact: true }).click();
  await page.getByLabel('Monto en pesos', { exact: true }).fill('200000');
  await page.getByText('Cambiar fecha o agregar detalles').click();
  await page.locator('input[name=reserved]').fill('50000');
  await page.getByRole('button', { name: 'Guardar ingreso', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.match(await page.locator('.daily-balance h1').textContent(), /720\.000/);
  assert.match(await page.locator('.office-note > p').textContent(), /Sus ingresos cubren/);
  await page.getByRole('button', { name: 'Pagué algo', exact: true }).click();
  await page.getByLabel('Monto en pesos', { exact: true }).fill('30000');
  await page.getByRole('button', { name: 'Consultorio', exact: true }).click();
  await page.getByText('Cambiar fecha o agregar detalles').click();
  await page.getByRole('textbox', { name: 'Concepto', exact: true }).fill('Laboratorio');
  await page.getByLabel('Lo pagué con dinero apartado para tratamientos').check();
  await page.getByRole('button', { name: 'Guardar gasto', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.match(await page.locator('.daily-balance h1').textContent(), /720\.000/);
  await page.getByRole('button', { name: 'Ver anteriores', exact: true }).click();
  assert.equal(await page.locator('.recent-list li').count(), 6);
  await page.getByRole('button', { name: 'Editar Laboratorio', exact: true }).click();
  await page.getByRole('button', { name: 'Eliminar este movimiento', exact: true }).click();
  await page.getByRole('button', { name: 'Eliminar movimiento', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.equal(await page.locator('.recent-list li').count(), 5);
  assert.match(await page.locator('.daily-balance h1').textContent(), /720\.000/);
  await page.getByLabel('Opciones').click();
  const download = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Descargar movimientos' }).click();
  assert.equal((await download).suggestedFilename(), 'natalia-movimientos.csv');
  await page.getByRole('button', { name: 'Cómo funciona' }).click();
  await page.keyboard.press('Escape');
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  // Nombres de fuentes, clasificación de gasto y periodo se conservan en el CSV.
  await page.getByRole('button', { name: 'Fuentes de ingreso', exact: true }).click();
  await page.getByRole('button', { name: 'Cambiar nombre de Clínica 1' }).click();
  await page.locator('input[name=source_name]').fill('Clínica Sonrisa');
  await page.getByRole('button', { name: 'Guardar nombre' }).click();
  await page.getByRole('button', { name: 'Cambiar nombre de Clínica Sonrisa' }).waitFor();
  await page.locator('input[name=source_name]').fill('Clínica Nueva');
  await page.locator('select[name=source_context]').selectOption('Clínica 2');
  await page.getByRole('button', { name: 'Agregar fuente' }).click();
  await page.getByRole('button', { name: 'Cambiar nombre de Clínica Nueva' }).waitFor();
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: 'Editar Pago de Clínica 1', exact: true }).click();
  await page.locator('input[name=competence_date]').fill('2026-08-15');
  await page.getByRole('button', { name: 'Guardar ingreso', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await page.getByRole('button', { name: 'Editar Gasto personal', exact: true }).click();
  await page.locator('select[name=category]').selectOption('Alimentación');
  await page.getByRole('button', { name: 'Guardar gasto', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await page.getByText('¿En qué se fue el dinero?', { exact: false }).click();
  await page.getByLabel('Ver gastos de').selectOption('Personal');
  assert.match(await page.locator('.spending-content').textContent(), /Alimentación.*30\.000/);
  await page.reload();
  await page.getByRole('heading', { name: '¿Cómo va el consultorio?' }).waitFor();
  const stored = await page.evaluate(() => JSON.parse(localStorage.getItem('natalia-finances-v1')));
  assert(stored.sources.some(s => s.name === 'Clínica Sonrisa'));
  assert(stored.sources.some(s => s.name === 'Clínica Nueva'));
  assert(stored.items.some(t => t.competence_date === '2026-08-15'));
  await page.getByLabel('Opciones').click();
  const enrichedDownload = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Descargar movimientos' }).click();
  const csvPath = await (await enrichedDownload).path();
  const { readFile } = await import('node:fs/promises');
  const csv = await readFile(csvPath, 'utf8');
  assert(csv.includes('ID persona'));
  assert(csv.includes('Fecha periodo'));
  assert(csv.includes('Clínica Sonrisa'));
  assert(csv.includes('2026-08-15'));
  assert(csv.includes('Alimentación'));
  assert(!csv.includes('"\'-30000"'), 'Flujo negativo debe exportarse como número');
  assert.equal(await page.getByRole('heading', { name: 'Notas, tal como pasó' }).count(), 0);
  await page.getByRole('button', { name: 'Tabla', exact: true }).click();
  await page.getByRole('columnheader', { name: 'Fecha', exact: true }).waitFor();
  assert.equal(await page.getByRole('columnheader', { name: 'Concepto' }).count(), 1);
  assert.equal(await page.getByRole('columnheader', { name: 'Moneda' }).count(), 1);
  for (const width of [320, 375]) {
    await page.setViewportSize({ width, height: 812 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'Tabla dentro de pantalla');
  }
  if (await page.locator('.options-menu').getAttribute('open') === null) await page.getByLabel('Opciones').click();
  await page.getByRole('button', { name: 'Salir', exact: true }).click();
  await page.getByLabel('Clave de acceso').fill('123456');
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await page.getByRole('button', { name: 'Entrada', exact: true }).waitFor();
  assert.match(await page.locator('.daily-brand').textContent(), /Diego/);
  assert.equal(await page.getByRole('heading', { name: '¿Cómo va el consultorio?' }).count(), 0);
  await page.getByRole('button', { name: 'Entrada', exact: true }).click();
  assert.equal(await page.getByRole('button', { name: 'Consultorio', exact: true }).count(), 0);
  assert.equal(await page.getByRole('button', { name: 'Clínica 1', exact: true }).count(), 0);
  await page.getByLabel('Moneda del movimiento').selectOption('USD');
  await page.getByLabel('Monto en dólares', { exact: true }).fill('150.25');
  await page.getByLabel('Concepto', { exact: true }).fill('Pago de Diego a Bancolombia');
  await page.getByRole('button', { name: 'Guardar ingreso', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await page.getByRole('group', { name: 'Moneda del saldo' }).getByRole('button', { name: 'USD', exact: true }).click();
  assert.match(await page.locator('.daily-balance h1').textContent(), /150,25.*USD/);
  await page.getByRole('button', { name: 'Salida', exact: true }).click();
  await page.getByLabel('Monto en dólares', { exact: true }).fill('20.10');
  assert.equal(await page.getByRole('button', { name: 'Consultorio', exact: true }).count(), 0);
  await page.getByRole('button', { name: 'Guardar gasto', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.match(await page.locator('.daily-balance h1').textContent(), /130,15.*USD/);
  await page.getByRole('group', { name: 'Moneda del saldo' }).getByRole('button', { name: 'COP', exact: true }).click();
  assert.match(await page.locator('.daily-balance h1').textContent(), /\$\s*0.*COP/);
  await page.getByRole('button', { name: 'Entrada', exact: true }).click();
  await page.getByLabel('Monto en pesos', { exact: true }).fill('200000');
  await page.getByRole('button', { name: 'Guardar ingreso', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.match(await page.locator('.daily-balance h1').textContent(), /200\.000.*COP/);

  await page.getByRole('button', { name: 'Tabla', exact: true }).click();
  await page.getByRole('cell', { name: 'Pago de Diego a Bancolombia' }).waitFor();
  assert.match(await page.locator('.income-total').textContent(), /200\.000.*COP/);
  await page.getByRole('group', { name: 'Moneda del saldo' }).getByRole('button', { name: 'USD', exact: true }).click();
  assert.match(await page.locator('.income-total').textContent(), /150,25.*USD/);
  assert.match(await page.locator('.expense-total').textContent(), /20,10.*USD/);
  assert.equal(await page.locator('.expense-total').evaluate(e => getComputedStyle(e).color), 'rgb(192, 71, 71)');
  await page.reload();
  await page.getByRole('button', { name: 'Tabla', exact: true }).click();
  await page.getByRole('cell', { name: 'Pago de Diego a Bancolombia' }).waitFor();
  assert.match(await page.locator('.daily-brand').textContent(), /Diego/);
  if (await page.locator('.options-menu').getAttribute('open') === null) await page.getByLabel('Opciones').click();
  await page.getByRole('button', { name: 'Salir', exact: true }).click();
  await page.getByLabel('Clave de acceso').fill('1357955');
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await page.getByRole('heading', { name: '¿Cómo va el consultorio?' }).waitFor();
  assert.equal(await page.getByText('Pago de Diego a Bancolombia', { exact: true }).count(), 0);
  const balanceBefore = await page.locator('.daily-balance h1').textContent();
  await page.getByRole('button', { name: 'Recibí dinero', exact: true }).click();
  await page.getByLabel('Monto en pesos', { exact: true }).fill('1650000');
  await page.getByRole('button', { name: 'Consultorio', exact: true }).click();
  await page.getByLabel('Concepto', { exact: true }).fill('Abono pendiente caso de prueba');
  await page.getByLabel('Abono de un tratamiento pendiente').check();
  await page.getByRole('button', { name: 'Guardar ingreso', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.equal(await page.locator('.daily-balance h1').textContent(), balanceBefore);
  await page.getByText('Abonos de tratamientos pendientes', { exact: true }).click();
  const incomeBeforeRelease = await page.locator('.income-total').textContent();
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: 'Tratamiento entregado · liberar' }).click();
  await page.getByText('No hay abonos pendientes registrados.').waitFor();
  assert.equal(await page.locator('.income-total').textContent(), incomeBeforeRelease);
  assert.notEqual(await page.locator('.daily-balance h1').textContent(), balanceBefore);
  await page.getByRole('button', { name: 'Pagué algo', exact: true }).click();
  await page.getByLabel('Monto en pesos', { exact: true }).fill('10000');
  await page.getByLabel('Concepto', { exact: true }).fill('Didi regreso a casa');
  await page.getByText('Se guardará como Personal · Transporte. Puedes cambiar la categoría.').waitFor();
  await page.getByRole('button', { name: 'Guardar gasto', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await page.getByRole('button', { name: 'Editar Didi regreso a casa' }).click();
  assert.equal(await page.locator('select[name=category]').inputValue(), 'Transporte');
  await page.getByRole('button', { name: 'Cerrar', exact: true }).click();
  assert.deepEqual(errors, []);
  console.log('OK: pantalla única, gasto sin nota/fecha/categoría, pagos en distintas fechas, saldo entre meses, consultorio, reservas existentes, edición/eliminación, persistencia, CSV y celular 320/375 px.');
} finally { await browser.close(); }
