import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const browser = await chromium.launch();
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1050 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(process.env.APP_URL || 'http://localhost:5173');
  await page.getByLabel('Clave de acceso').fill('0000000');
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await page.getByText('Esa clave no es correcta. Inténtalo de nuevo.').waitFor();
  await page.getByLabel('Clave de acceso').fill('1357955');
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await page.getByRole('heading', { name: '¿Cómo va el consultorio?' }).waitFor();
  assert.equal(await page.getByRole('navigation').count(), 0, 'Una sola pantalla sin navegación de dashboard');
  await page.screenshot({ path: 'artifacts/desktop.png', fullPage: true });
  for (const width of [375, 320]) {
    await page.setViewportSize({ width, height: 812 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `Sin desbordamiento a ${width}px`);
    if (width === 375) await page.screenshot({ path: 'artifacts/mobile.png', fullPage: true });
  }
  await page.setViewportSize({ width: 375, height: 812 });
  await page.getByLabel('Opciones').click();
  await page.getByRole('button', { name: 'Empezar desde cero' }).click();
  await page.getByRole('button', { name: 'Borrar y empezar' }).click();
  assert.match(await page.locator('.daily-balance h1').textContent(), /\$\s*0/);
  await page.getByLabel('Opciones').click();
  await page.getByRole('button', { name: 'Recibí dinero', exact: true }).click();
  await page.getByLabel('Monto en pesos', { exact: true }).fill('500000');
  await page.getByRole('button', { name: 'Clínica 1', exact: true }).click();
  await page.getByText('Agregar nota o cambiar fecha').click();
  const earlier = new Date(); earlier.setMonth(earlier.getMonth() - 1); earlier.setDate(15);
  const previousDate = `${earlier.getFullYear()}-${String(earlier.getMonth() + 1).padStart(2, '0')}-15`;
  await page.locator('input[name=date]').fill(previousDate);
  await page.getByRole('button', { name: 'Guardar ingreso', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.match(await page.locator('.daily-balance h1').textContent(), /500\.000/);
  await page.getByRole('button', { name: 'Recibí dinero', exact: true }).click();
  await page.getByLabel('Monto en pesos', { exact: true }).fill('200000');
  await page.getByRole('button', { name: 'Clínica 2', exact: true }).click();
  await page.getByRole('button', { name: 'Guardar ingreso', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.match(await page.locator('.daily-balance h1').textContent(), /700\.000/);
  // El gasto se guarda sin abrir detalles ni escribir nota, categoría o fecha.
  await page.getByRole('button', { name: 'Pagué algo', exact: true }).click();
  await page.getByLabel('Monto en pesos', { exact: true }).fill('20000');
  assert.equal(await page.locator('.optional-details').getAttribute('open'), null);
  await page.getByRole('button', { name: 'Guardar gasto', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.match(await page.locator('.daily-balance h1').textContent(), /680\.000/);
  await page.getByRole('button', { name: 'Pagué algo', exact: true }).click();
  await page.getByLabel('Monto en pesos', { exact: true }).fill('100000');
  await page.getByRole('button', { name: 'Consultorio', exact: true }).click();
  await page.getByRole('button', { name: 'Guardar gasto', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.match(await page.locator('.daily-balance h1').textContent(), /580\.000/);
  assert.match(await page.locator('.office-note > p').textContent(), /Le faltan.*100\.000/);
  await page.reload();
  await page.getByRole('heading', { name: '¿Cómo va el consultorio?' }).waitFor();
  assert.match(await page.locator('.daily-balance h1').textContent(), /580\.000/);
  await page.getByRole('button', { name: 'Editar Gasto personal', exact: true }).click();
  await page.getByLabel('Monto en pesos', { exact: true }).fill('30000');
  await page.getByRole('button', { name: 'Guardar gasto', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.match(await page.locator('.daily-balance h1').textContent(), /570\.000/);
  await page.getByRole('button', { name: 'Recibí dinero', exact: true }).click();
  await page.getByLabel('Monto en pesos', { exact: true }).fill('200000');
  await page.getByText('Agregar nota o cambiar fecha').click();
  await page.locator('input[name=reserved]').fill('50000');
  await page.getByRole('button', { name: 'Guardar ingreso', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.match(await page.locator('.daily-balance h1').textContent(), /720\.000/);
  assert.match(await page.locator('.office-note > p').textContent(), /Sus ingresos cubren/);
  await page.getByRole('button', { name: 'Pagué algo', exact: true }).click();
  await page.getByLabel('Monto en pesos', { exact: true }).fill('30000');
  await page.getByRole('button', { name: 'Consultorio', exact: true }).click();
  await page.getByText('Agregar nota o cambiar fecha').click();
  await page.locator('input[name=description]').fill('Laboratorio');
  await page.getByLabel('Lo pagué con dinero apartado para tratamientos').check();
  await page.getByRole('button', { name: 'Guardar gasto', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.match(await page.locator('.daily-balance h1').textContent(), /720\.000/);
  await page.getByRole('button', { name: 'Ver anteriores', exact: true }).click();
  assert.equal(await page.locator('.recent-list li').count(), 6);
  await page.getByRole('button', { name: 'Editar Laboratorio', exact: true }).click();
  await page.getByRole('button', { name: 'Eliminar este movimiento', exact: true }).click();
  await page.getByRole('button', { name: 'Eliminar movimiento', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.equal(await page.locator('.recent-list li').count(), 5);
  assert.match(await page.locator('.daily-balance h1').textContent(), /720\.000/);
  await page.getByLabel('Opciones').click();
  const download = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Descargar movimientos' }).click();
  assert.equal((await download).suggestedFilename(), 'natalia-movimientos.csv');
  await page.getByRole('button', { name: 'Cómo funciona' }).click();
  await page.keyboard.press('Escape');
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  // Nombres de fuentes, clasificación de gasto y periodo se conservan en el CSV.
  await page.getByRole('button', { name: 'Fuentes de ingreso', exact: true }).click();
  await page.getByRole('button', { name: 'Cambiar nombre de Clínica 1' }).click();
  await page.locator('input[name=source_name]').fill('Clínica Sonrisa');
  await page.getByRole('button', { name: 'Guardar nombre' }).click();
  await page.getByRole('button', { name: 'Cambiar nombre de Clínica Sonrisa' }).waitFor();
  await page.locator('input[name=source_name]').fill('Clínica Nueva');
  await page.locator('select[name=source_context]').selectOption('Clínica 2');
  await page.getByRole('button', { name: 'Agregar fuente' }).click();
  await page.getByRole('button', { name: 'Cambiar nombre de Clínica Nueva' }).waitFor();
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: 'Editar Pago de Clínica 1', exact: true }).click();
  await page.locator('input[name=competence_date]').fill('2026-08-15');
  await page.getByRole('button', { name: 'Guardar ingreso', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await page.getByRole('button', { name: 'Editar Gasto personal', exact: true }).click();
  await page.locator('select[name=category]').selectOption('Alimentación');
  await page.getByRole('button', { name: 'Guardar gasto', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await page.getByText('¿En qué se fue el dinero?', { exact: false }).click();
  await page.getByLabel('Ver gastos de').selectOption('Personal');
  assert.match(await page.locator('.spending-content').textContent(), /Alimentación.*30\.000/);
  await page.reload();
  await page.getByRole('heading', { name: '¿Cómo va el consultorio?' }).waitFor();
  const stored = await page.evaluate(() => JSON.parse(localStorage.getItem('natalia-finances-v1')));
  assert(stored.sources.some(s => s.name === 'Clínica Sonrisa'));
  assert(stored.sources.some(s => s.name === 'Clínica Nueva'));
  assert(stored.items.some(t => t.competence_date === '2026-08-15'));
  await page.getByLabel('Opciones').click();
  const enrichedDownload = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Descargar movimientos' }).click();
  const csvPath = await (await enrichedDownload).path();
  const { readFile } = await import('node:fs/promises');
  const csv = await readFile(csvPath, 'utf8');
  assert(csv.includes('ID persona'));
  assert(csv.includes('Fecha periodo'));
  assert(csv.includes('Clínica Sonrisa'));
  assert(csv.includes('2026-08-15'));
  assert(csv.includes('Alimentación'));
  assert(!csv.includes('"\'-30000"'), 'Flujo negativo debe exportarse como número');
  assert.deepEqual(errors, []);
  console.log('OK: pantalla única, gasto sin nota/fecha/categoría, pagos en distintas fechas, saldo entre meses, consultorio, reservas existentes, edición/eliminación, persistencia, CSV y celular 320/375 px.');
} finally { await browser.close(); }
