import { it,expect,vi,afterEach } from 'vitest';
import { financeSnapshot,responseText,type LedgerRow } from '../lib/chat';
import handler from '../api/chat';
import type { IncomingMessage,ServerResponse } from 'node:http';
afterEach(()=>{vi.unstubAllEnvs();vi.unstubAllGlobals();});
const row=(id:string,kind:string,amount:number,flow_type:string,other:Partial<LedgerRow>={}):LedgerRow=>({id,date:'2026-10-01',kind,amount,flow_type,currency:'USD',category:'Otros',description:'Concepto',context:'Personal',reserved:0,from_reserve:false,...other});
it('calcula todo el histórico, separa monedas y deja las transferencias fuera de PyL',()=>{const data=financeSnapshot([row('1','income',3000,'opening_balance',{account_id:'arq'}),row('2','expense',98,'transfer',{account_id:'arq',transfer_role:'sent'}),row('3','expense',2,'operating',{account_id:'arq',transfer_role:'fee'}),row('4','income',330000,'transfer',{currency:'COP',account_id:'banco'}),row('5','income',999,'operating',{date:'2026-11-01'})],[{id:'arq',name:'ARQ',currency:'USD'},{id:'banco',name:'Banco',currency:'COP'}],[],'2026-10-01');expect(data.cash_by_currency).toEqual({COP:330000,USD:2900});expect(data.available_by_currency).toEqual({COP:330000,USD:2900});expect(data.accounts[0].balance).toBe(2900);expect(data.monthly_operating).toHaveLength(1);expect(data.transfer_fees_by_currency.USD).toBe(2);});
it('mantiene totales completos cuando el detalle supera 200 registros',()=>{const data=financeSnapshot(Array.from({length:250},(_,i)=>row(String(i),'expense',0.1,'operating')),[],[],'2026-10-01');expect(data.movements).toHaveLength(200);expect(data.cash_by_currency.USD).toBe(-25);expect(data.monthly_operating[0].amount).toBe(25);});
it('no muestra una respuesta incompleta como análisis terminado',()=>{expect(()=>responseText({status:'incomplete',output:[]})).toThrow();expect(responseText({status:'completed',output:[{type:'message',content:[{type:'output_text',text:'Listo'}]}]})).toBe('Listo');});
async function call(body:unknown,authorization?:string){let text='';const res={statusCode:200,setHeader:vi.fn(),end:(v:string)=>{text=v;}} as unknown as ServerResponse;await handler({method:'POST',headers:{authorization},body} as unknown as IncomingMessage,res);return {status:res.statusCode,body:JSON.parse(text)};}
it('rechaza preguntas sin sesión antes de consultar datos o IA',async()=>{const fetch=vi.fn();vi.stubGlobal('fetch',fetch);expect((await call({question:'Mis cuentas'})).status).toBe(401);expect(fetch).not.toHaveBeenCalled();});
it('obtiene identidad y filtros de la sesión, ignora la persona enviada por el cliente y guarda el snapshot',async()=>{vi.stubEnv('VITE_SUPABASE_URL','https://example.supabase.co');vi.stubEnv('VITE_SUPABASE_PUBLISHABLE_KEY','public-key');vi.stubEnv('OPENAI_API_KEY','test-only');let snapshot:any;const requests:{url:string;auth:string|null}[]=[];vi.stubGlobal('fetch',vi.fn(async(url:string|URL,options:RequestInit={})=>{const u=String(url);requests.push({url:u,auth:new Headers(options.headers).get('authorization')});if(u.includes('/auth/v1/user'))return Response.json({id:'diego-id',email:'diego-access@nts-financial.example.com'});if(u.includes('api.openai.com'))return Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:'No tienes movimientos registrados.'}]}]});if(options.method==='HEAD')return new Response(null,{headers:{'content-range':'*/0'}});if(u.includes('/finance_chat')&&options.method==='POST'){const data=JSON.parse(String(options.body));snapshot=data;return Response.json({id:'chat-id',question:data.question,answer:data.answer});}return Response.json([]);}));const result=await call({question:'Mis cuentas',person_tag:'natalia',user_id:'natalia-id'},'Bearer diego-session');expect(result.status).toBe(200);expect(snapshot.person_tag).toBe('diego');expect(snapshot.user_id).toBe('diego-id');expect(snapshot.snapshot.person).toBe('diego');for(const r of requests.filter(r=>r.url.includes('/rest/v1/') && !r.url.includes('/exchange_rates') && !r.url.includes('select=id%2Cquestion%2Canswer'))){expect(r.url).toContain('user_id=eq.diego-id');expect(r.auth).toBe('Bearer diego-session');}expect(requests.filter(r=>r.url.includes('/rest/v1/')&& !r.url.includes('/finance_chat')) .every(r=>r.url.includes('person_tag=eq.diego') || r.url.includes('/exchange_rates'))).toBe(true);});

it('no mezcla reservas de consultorio entre monedas o espacios',()=>{const data=financeSnapshot([row('1','income',100,'operating',{context:'Consultorio',reserved:30}),row('2','expense',50,'operating',{context:'Consultorio',currency:'COP',from_reserve:true})],[],[],'2026-10-01');expect(data.reserved_by_currency).toEqual({COP:0,USD:30});expect(data.available_by_currency).toEqual({COP:-50,USD:70});});

it('protege abonos completos ante pagos genéricos y libera solo en la fecha de entrega',()=>{const rows=[row('abono','income',100,'operating',{context:'Consultorio',patient_advance:true,reserved:100,reserve_release_date:'2026-10-02'}),row('lab','expense',20,'operating',{context:'Consultorio',from_reserve:true})];expect(financeSnapshot(rows,[],[],'2026-10-01').available_by_currency.USD).toBe(-20);const delivered=financeSnapshot(rows,[],[],'2026-10-02');expect(delivered.cash_by_currency.USD).toBe(80);expect(delivered.available_by_currency.USD).toBe(80);expect(delivered.patient_advances_pending).toHaveLength(0);});
it('responde y guarda consultas básicas sin clave de IA, usando solo registros del perfil',async()=>{
 vi.stubEnv('VITE_SUPABASE_URL','https://example.supabase.co');vi.stubEnv('VITE_SUPABASE_PUBLISHABLE_KEY','public-key');vi.stubEnv('OPENAI_API_KEY','');
 const urls:string[]=[];let saved:any;
 vi.stubGlobal('fetch',vi.fn(async(url:string|URL,options:RequestInit={})=>{
  const u=String(url);urls.push(u);
  if(u.includes('/auth/v1/user'))return Response.json({id:'natalia-id',email:'natalia-access@nts-financial.example.com'});
  if(options.method==='HEAD')return new Response(null,{headers:{'content-range':'*/0'}});
  if(u.includes('/transactions'))return Response.json([row('abono','income',100,'operating',{context:'Consultorio',patient_advance:true,reserved:100})]);
  if(u.includes('/finance_chat')&&options.method==='POST'){saved=JSON.parse(String(options.body));return Response.json({id:'chat-id',question:saved.question,answer:saved.answer});}
  return Response.json([]);
 }));
 const result=await call({question:'¿Cuánto está apartado?',person_tag:'diego'},'Bearer natalia-session');
 expect(result.status).toBe(200);expect(result.body.answer).toContain('100 USD');expect(saved.model).toBe('recorded-rules-v1');expect(saved.person_tag).toBe('natalia');
 expect(urls.some(url=>url.includes('api.openai.com'))).toBe(false);
 expect(urls.filter(url=>url.includes('/transactions')).every(url=>url.includes('user_id=eq.natalia-id')&&url.includes('person_tag=eq.natalia'))).toBe(true);
});
