import { useEffect, useRef, useState, type FormEvent } from 'react';
import { MessageCircle, X } from 'lucide-react';
import { supabase } from './supabase';
type Exchange={id:string;question:string;answer:string};
export function FinanceChat({ userId, personName }: { userId?: string; personName: string }) {
 const [open,setOpen]=useState(false),[history,setHistory]=useState<Exchange[]>([]),[question,setQuestion]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const end=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!open)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false);};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[open]);
 useEffect(()=>{if(!open||!userId||!supabase)return;let active=true;void supabase.from('finance_chat').select('id,question,answer').eq('user_id',userId).order('created_at',{ascending:false}).limit(30).then(({data,error})=>{if(active){if(error)setError('No pudimos cargar la conversación.');else setHistory((data||[]).reverse());}});return()=>{active=false;};},[open,userId]);
 useEffect(()=>{end.current?.scrollIntoView({block:'nearest'});},[history,busy]);
 async function send(e:FormEvent){e.preventDefault();if(!question.trim()||busy)return;if(!supabase||!userId){setError('El chat necesita tu sesión de Supabase.');return;}setBusy(true);setError('');try{const {data:{session}}=await supabase.auth.getSession();if(!session)throw Error('Vuelve a iniciar sesión.');const res=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({question:question.trim()})});const body=await res.json();if(!res.ok)throw Error(body.error||'No pudimos consultar el chat.');setHistory(h=>[...h,body]);setQuestion('');}catch(e){setError(e instanceof Error?e.message:'Revisa tu conexión.');}finally{setBusy(false);}}
 return <><button className="chat-bubble" aria-label="Abrir asistente de finanzas" onClick={()=>setOpen(!open)}><MessageCircle size={23}/></button>{open&&<section className="finance-chat" role="dialog" aria-label={`Asistente de ${personName}`}><header><strong>Tus datos · {personName}</strong><button aria-label="Cerrar asistente" onClick={()=>setOpen(false)}><X size={20}/></button></header><div className="chat-messages"><p className="chat-intro">Consulta ingresos, gastos, cuentas y abonos.</p>{history.map(h=><div key={h.id}><p className="chat-question">{h.question}</p><p className="chat-answer">{h.answer}</p></div>)}{busy&&<p role="status">Revisando tus registros…</p>}<div ref={end}/></div>{error&&<p role="alert" className="error">{error}</p>}<form onSubmit={send}><label className="sr-only" htmlFor="chat-question">Tu pregunta</label><textarea autoFocus id="chat-question" required maxLength={2000} rows={2} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="¿Cómo van mis gastos?"/><button className="primary" disabled={busy||!question.trim()}>Enviar</button></form></section>}</>;
}
